# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Selected Works
titleurl: derekmisler.github.io
fullname: Derek Misler
url: "http://derekmisler.github.io"
email: derekmisler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Derek is a front-end developer with a design
 background and over 10 years of experience. 
 He is also available for hire. Click here to learn more.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: derekmisler
linkedin_username: derekmisler
github_username:  derekmisler

# Build settings
markdown: kramdown
